rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'ci / test (12, auto-label) (pull_request)'
    - 'ci / test (12, blunderbuss) (pull_request)'
    - 'ci / test (12, buildcop) (pull_request)'
    - 'ci / test (12, conventional-commit-lint) (pull_request)'
    - 'ci / test (12, failurechecker) (pull_request)'
    - 'ci / test (12, gcf-utils) (pull_request)'
    - 'ci / test (12, generate-bot) (pull_request)'
    - 'ci / test (12, header-checker-lint) (pull_request)'
    - 'ci / test (12, label-sync) (pull_request)'
    - 'ci / test (12, merge-on-green) (pull_request)'
    - 'ci / test (12, monitoring-system/data-processor) (pull_request)'
    - 'ci / test (12, release-please) (pull_request)'
    - 'ci / test (12, slo-stat-bot) (pull_request)'
    - 'ci / test (12, snippet-bot) (pull_request)'
    - 'ci / test (12, sync-repo-settings) (pull_request)'
    - 'ci / test (12, trusted-contribution) (pull_request)'
    - 'ci / test (10, auto-label) (pull_request)'
    - 'ci / test (10, blunderbuss) (pull_request)'
    - 'ci / test (10, buildcop) (pull_request)'
    - 'ci / test (10, conventional-commit-lint) (pull_request)'
    - 'ci / test (10, failurechecker) (pull_request)'
    - 'ci / test (10, gcf-utils) (pull_request)'
    - 'ci / test (10, generate-bot) (pull_request)'
    - 'ci / test (10, header-checker-lint) (pull_request)'
    - 'ci / test (10, label-sync) (pull_request)'
    - 'ci / test (10, merge-on-green) (pull_request)'
    - 'ci / test (10, monitoring-system/data-processor) (pull_request)'
    - 'ci / test (10, release-please) (pull_request)'
    - 'ci / test (10, slo-stat-bot) (pull_request)'
    - 'ci / test (10, snippet-bot) (pull_request)'
    - 'ci / test (10, sync-repo-settings) (pull_request)'
    - 'ci / test (10, trusted-contribution) (pull_request)'
    - 'ci / Go tests (packages/buildcop) (pull_request)'
    - 'ci / Go tests (serverless-scheduler-proxy) (pull_request)'
    - 'ci / Bash tests (scripts) (pull_request)'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: Googlers
    permission: pull
  - team: github-automation
    permission: push
  - team: yoshi-admins
    permission: admin
